### ISSUE TITLE
Partisans and Soviet

### ISSUE THREAD

**Issue by MintyTea** [BSData/boltaction#100]
For Bolt Action V10 When I made a random roster without caring for the roster errors it told me my partisans were missing tanks and other equipment they cant access. Also Civilian cars have a MMG as rating and Guerrilla warriors, Parti Cavalry, Parti Early war squad and Parti inexperienced cant use any weapons at all without roster error. Also with the B-6 as command vehicle it says I cant have more than 1 command vehicle evens tho that's the only one

**Comment by Triarius94** [comment]
Fixed
