### ISSUE TITLE
[Anon] Bug report: BA2 - Armies of the  Soviet Union.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/boltaction#113]
**File:** BA2 - Armies of the  Soviet Union.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Frontnik Commissar is missing for the Soviet Army as a Choice. He can be found in the Stalingrad Campaign Book on Pagr 119 and should be available for both the Generic Soviet Reinforced Platoon aswell as the Stalingrad Sector.

Would be cool if you could add him anytime soon!

**Comment by Triarius94** [comment]
added
