### ISSUE TITLE
[Anon] Bug report: BA2 - Partisans.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/boltaction#116]
**File:** BA2 - Partisans.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When I attempt to make a Partisans list in Bolt Action 2.0 v5, if I select Partisans v5, no select force org screen comes up - it creates the army list without the ability to add units, only the theater selector is shown.

**Comment by Triarius94** [comment]
fixed, update your data
