### ISSUE TITLE
Bolt Action Armies of Germany Panzerbuchse 41 incorrect Penentration values. SD KFZ251/1 Pioneer

### ISSUE THREAD

**Issue by tl14green** [BSData/boltaction#118]
According to the Armies of Germany book the Panzerbuchse 41 is a light anti tank gun Range 48 inches. Its base penentration is +4. At ranges up to 12 inches it is increased by +2 making it +6 penentration and ranges over 24 inches it is reduced by -2 making it +2 penentration.

In the army list for the SD KFZ251/1 pioneer option it is down as an Anti tank rifle and as a result all the other values are incorrect.

Thanks for all your efforts.

**Comment by Triarius94** [comment]
Fixed

**Comment by tl14green** [comment]
Thank you very much for your help. 
Have a great gaming December.

    On Friday, 9 December 2022 at 10:01:16 GMT, Lorenzo De Florio ***@***.***> wrote:  
 
 


Fixed
