### ISSUE TITLE
Panzerschreck team is missing on German Generic Reinforced Platoon

### ISSUE THREAD

**Issue by JaakkoTusa** [BSData/boltaction#119]
**Describe the bug**
Panzerschreck team is not shown in Anti-Tank team options. There are only Anti-tank Rifle Team and Goliath Demoliton Team
If you change Theater Selector from Generic Reinforced Platoon to something else (for example "1945: Last Levy"), Panzerschreck option is available. This option should be available also in Generic Reinforced Platoon.

**To Reproduce**
1. Click New Roster
2. Click Add Force
3. Select Armies of Germany and Reinforced Platoon
4. Scroll down to Infantry Support
5. Find Anti-tank Team 
6. Click + sign to add that to your roster
7.  See option on right side panel; there is no Panzerschreck Team in selection

**Expected behavior**

There should be Panzerschreck Team option available for Anti-tank Team.

**Screenshots**
![image](https://user-images.githubusercontent.com/115152744/225267722-c72741a2-c8e5-4d10-a0cb-23b66ac3e8b6.png)
![image](https://user-images.githubusercontent.com/115152744/225267620-be6c2a33-2294-47c9-938a-bf47f060edee.png)

**Device and data (please complete the following information):**
 - OS: [Windows 10]
 - BattleScribe version [2.03.21]
 - Release version [2.0 v8]

**Additional context**

**Comment by Triarius94** [comment]
fixed
