### ISSUE TITLE
[Anon] Bug report: BA2 - Armies of Hungary.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/boltaction#122]
**File:** BA2 - Armies of Hungary.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** 1. Experienced Honved squads can have 2 panzerfausts.
2 PÁNCÉLEREM is misspelled.
3. 2nd army squads can have either mortar or lmg, not both

**Comment by Triarius94** [comment]
Fixed
