### ISSUE TITLE
[Anon] Bug report: BA2 - Armies of Italy.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/boltaction#124]
**File:** BA2 - Armies of Italy.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Alpini (Case Blue) squads throw up errors because of their in-built Mountaineers rule.

**Comment by Triarius94** [comment]
Fixed

**Comment by Triarius94** [comment]
Fixed
