### ISSUE TITLE
US Airborne point cost

### ISSUE THREAD

**Issue by fpastenv** [BSData/boltaction#125]
**Describe the bug**
The +5 BAR on Paratrooper Squad seems wrong. 

Veteran Paratrooper squad (Late) – 7 men – 98
x1 BAR – 5
Anti-Tank Grenades – 14
Stubborn

That unit costs 122 points on Batttlescribe and should be costing 117 points.

**Thank you very much for your work!!**

**Comment by Triarius94** [comment]
fixed
