### ISSUE TITLE
Incorrect Weapon Assignments for US Army M21 Mortar Carrier

### ISSUE THREAD

**Issue by Ninponeer** [BSData/boltaction#130]
For "Armies of the United States":
The M21 Mortar Carrier has incorrect weapon assignments.  Currently there are only options for 2 pintle-mounted HMG w/ 360 arc of fire.

The M21 Mortar Carrier SHOULD have the following weapons:
1 Pintle-mounted HMG with 360 arc of fire
&
1 hull-mounted front-facing medium mortar

![image](https://github.com/BSData/boltaction/assets/91558838/19c1a935-5522-4e49-8ad9-988d084813f4)

**Comment by Triarius94** [comment]
fixed
