### ISSUE TITLE
[Anon] Bug report: BA2 - Armies of Hungary.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/boltaction#131]
**File:** BA2 - Armies of Hungary.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Incorrect point values: Parachute Assault antitank grenades should be 2pts per man. Although it is not in the book, this is considered an error.  Border Guards have troops with smg's listed as 3 pts per man, it should be 3 pts in addition to the 11pt cost.

**Comment by Triarius94** [comment]
fixed
