### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by enricob15** [BSData/boltaction#132]
### Reference contact

@Triarius94

### Your Discord

Enricob15

### Additional information

hi i would like to join. thanks

**Comment by Mad-Spy** [comment]
@Triarius94 can you deal with this please. Comment (/)invite to add this user to the repo, or close the issue if not.

**Comment by enricob15** [comment]
Is there something wrong?

**Comment by Triarius94** [comment]
added the user
