### ISSUE TITLE
Armies of France Corrections

### ISSUE THREAD

**Issue by Merlin5790** [BSData/boltaction#134]
Quite a few issues with this catalogue

Free Units should have an option for the Hurriedly Conscripted Troops rule, giving an extra Inexperience Squad identical to the cheapest of three Inexperienced Squads already in your force.

Infantry Section 
NCO should default to Rifle instead of getting an error message telling you to choose.
Extra soldier armed with Pistol should default to being armed with a pistol instead of getting an error message telling you to choose.

Dragon Portes
Squad should start with 1 NCO and 4 soldiers by default. currently set to 1

French Foreign Legion
No reason to select Veterans for this unit. They are Veteran by default
NCO should default to Rifle instead of getting an error message telling you to choose.
Extra soldier armed with Pistol should default to being armed with a pistol instead of getting an error message telling you to choose.
There's an error saying "...cannot have any selections of Stubborn (Hidden)"

Cavalry Sections
Regular and Veteran squads should have 1 NCO and 5 soldiers by default. Currently set to 4 soldiers.

AMR33 & AMR35
Either should be split or an extra option to pick which version you are using as only AMR35 has the option to upgrade to an HMG

Renault EU Chenillette (Towing vehicle)
Has the option for a 360 degree MMG for +15pts. It should only get the Forward Facing MMG option.

**Comment by Merlin5790** [comment]
I'm trying to make lists, but the way the units have been set up the catalogue just doesn't work as it should. 

For example, if I want an Inexperienced Infantry Section of 1 NCO and 4 Soldiers, one of them with a VB Launcher. Instead of the VB Launcher being a 20pt upgrade to the unit, its costed as 27pts meaning that I'm paying for an extra soldier in addition to paying for the weapon. Which means that I'll have a squad of 1 NCO and 5 Soldiers, when I only wanted 4 Soldiers.

In my opinion, the whole army list could do with an overhaul to separate the cost of the weapon options from the cost of the troopers.

**Comment by Triarius94** [comment]
fixed all, in the next update it shoud be ok
