### ISSUE TITLE
[Anon] Bug report: BA - Japan.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/boltaction#44]
**File:** BA - Japan.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The type 1 47mm anti-tank fun is not a choice available in the artillery section when designing an army. It appears to have the 37mm light anti-tank fun twice for selection.

**Comment by Toreador13** [comment]
Fixed in v10
