### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by ZettaCrash** [BSData/boltaction#72]
I simply wish to update some of the Bolt Action files for the BA repository. I am sick and tired of my personal corrections being overwritten whenever I update repository and it seems the issues pertaining to Bolt Action have persisted for some time. At the very least, I wish to update the major armies so that I can correct all the point values, costs, and have them the units in question carry the correct equipment.

**Comment by Toreador13** [comment]
I don't think I have access to BSData/Boltaction to give access there, but those are the old repositories. I started a new Bolt Action 2.0 set of files, and had gotten some done on there, but ran out of time. I have given you an invite to that one. Might be a better starting point.

**Comment by larscevensen** [comment]
I have the same issue. Both with wrong data and missing theatre selectors. I would be happy to assist in updating the data to v2.0.

**Comment by amis92** [comment]
I guess I'll leave you to it then, @Toreador13. When you are ready/want to push to BSData/need assistance, please summon me.

**Comment by Mikey-Consto** [comment]
where can we access the BA2 files?
