### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by larscevensen** [BSData/boltaction#73]
I would like to help with keeping the data up to date as well as establishing the missing theatre selectors

**Comment by aleviwv** [comment]
I have updated germany, usa, britian, france

**Comment by aleviwv** [comment]
I have the files on my laptop updated

**Comment by Mikey-Consto** [comment]
awesome!!

**Comment by zev18120zev** [comment]
Maibe add. The netherlands an norway an sole new units from the books
