### ISSUE TITLE
Bug report: BA - Armies of the Soviet Union.catz scenarios have no free units

### ISSUE THREAD

**Issue by moozaad** [BSData/boltaction#80]
Pg 41. "Quality of quantity rule" this implies that all scenarios still get their free infantry unit, in addition of the optional swapping out for an inexperienced su-76,medium mortar or ZiS-3.

Pg 21. confirms this with "This free squad is in addition to units chosen from whatever Selector is used."

I suppose this is a 2 part bug:
1. Scenarios need their free squads
2. 1944 Scenarios should be able to select the free squad replacements.

**Comment by Triarius94** [comment]
they are not official rules , they are advices on the rulebbok, closed, free rifle squad added
