### ISSUE TITLE
Bug report: BA - Armies of the Soviet Union.catz Lend lease units from 1941

### ISSUE THREAD

**Issue by moozaad** [BSData/boltaction#81]
Pg 56 of soviet book. Not scenario specific but any force "themed" as 1941 onwards. This is not an optional rule and can be applied always.

T-60 -> Valentine
T-70 -> M3 stuart/ Tetrarch
SU-85 -> M10 Wolverine
T-34 -> M3 Lee / M4 Sherman
KV-1S -> Churchill / Matilda

BA-64 -> M3 Scout

Tokarev M4 -> M17 AA truck

Half track -> M5 Halftrack
Komsomolets -> Bren Carrier
Gaz Jeep -> Jeep / Seep

I think it'd probably just be easiest to add these entries to all forces and apply the same rules as their alternatives.

**Comment by Triarius94** [comment]
All lend lease added
