### ISSUE TITLE
Bug report: BA - Armies of the Soviet Union.catz/french/japanese no option to reduce moral range bonus on armoured platoons

### ISSUE THREAD

**Issue by moozaad** [BSData/boltaction#82]
pg. 12 tank war
Soviet armoured platoons (and french and japanese) can optionally reduce their moral range to 6" from 12" for a reduction to command vehicle cost of 10pts (ie. 25pts reduced to 15pts), and can not use "radio networks", ie. platoon/company/battalion commander.

**Comment by Triarius94** [comment]
added
