### ISSUE TITLE
Bug report: BA - Armies of the China.catz A Bunch of smaller issues

### ISSUE THREAD

**Issue by r0sshk** [BSData/boltaction#84]
Big Sword Squad and German-Trained Nationalist Squad don't become visible for nationalist forces, because it checks vs parent, rather than vs Force.

Also, Guerilla Squads do not have the correct point numbers per model.

**Comment by Toreador13** [comment]
This needs to be looked at in the v2.0 version of the file. Hopefully next week. Battlescribe has changed a lot since i first made that file.

**Comment by Triarius94** [comment]
Fixed
