### ISSUE TITLE
Bug report: BA - Armies of Great Britain.catz | Light Artillery Costs and Options

### ISSUE THREAD

**Issue by westphalentroll** [BSData/boltaction#85]
Light Artillery has some issues regarding experience, costs and Options.

1. Inexperienced is no valid option
2. Costs for Regualr are at 55 Points, Veteran at 66 Points
3. Spotter is a valid option for both Regular and Veteran.

**Comment by Toreador13** [comment]
This should be updated in the 2.0 version of the files next week.
