### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by MichalKacperKaczmarek** [BSData/boltaction#86]
Hello
I want to update bolt action for british reinforced selector and maybe RM Commando.
Since last commit was 3 years ago I want to make this myself :).

Best regards
Michal

**Comment by amis92** [comment]
Hello, @MichalKacperKaczmarek . Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/boltaction/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
