### ISSUE TITLE
US: M3 Stuart light tank

### ISSUE THREAD

**Issue by torbjorn** [BSData/boltaction#89]
It looks like the May 2019 updates for this vehicle hasn't been incorporated.

It should have a single hull mounted MMG, optionally 2LMGs for 15pts, optionally a pintle mounted MMG for 15pts.

Nothing of this is reflected in the current data file

**Comment by torbjorn** [comment]
It should also have a 10pt price deduction, from 125 down to 115 for regular for example, which is not implemented.

**Comment by Toreador13** [comment]
I haven't made these changes yet, was this in the original files or the new Bolt Action 2.0 files? I am actively working on the 2.0 files so will see if I can propagate the changes there.

**Comment by torbjorn** [comment]
They're in the FAQ and Errata of May 2019:
http://www.warlordgames.com/new-bolt-action-faq-event/

T.
