### ISSUE TITLE
[Anon] Bug report: BA-AotUS-1943 - Operation Avalanche.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/boltaction#91]
**File:** BA-AotUS-1943 - Operation Avalanche.catz

**BattleScribe version:** 2.03.01

**Platform:** Android

**Dropbox:** No

**Description:** No Light Artillery in the Artillery section. No light Howitzer. Medium Machine Gun Team selector should allow up to 3 MUGs.

**Comment by Triarius94** [comment]
fixed
